const products = [
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Samsung A11", price:250,image:"/images/pic (1).jpg"},
    {name:"Motorola comon 11", price:500,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:250,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Nokia comon 11", price:200,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:3500,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno comon 11", price:2500,image:"/images/pic (1).jpg"},
]
